### ISSUE TITLE
when using regorus as lambda layer

### ISSUE THREAD

**Issue by Daniel-Zafrir-1998** [microsoft/regorus#338] opened 2024-10-29 10:15 UTC
Hey there, I’m using the regorus package, which I’ve set up with Python bindings, and everything works fine on my local machine. But when I try to deploy it as a Lambda layer, I get an error saying that the module regorus can’t be found.

After setting up the Python bindings, does the Lambda function need the original regorus-main files for it to work, or can I rely solely on the installed files from the Python package?

If I installed regorus-0.2.2-cp310-none-win_amd64.whl on my Windows machine, then zipped those files for the Lambda layer, could this cause the "module not found" issue due to platform differences?

**Comment by anakrish** [comment] 2024-10-29 15:44
@Daniel-Zafrir-1998 One possible cause for module not being found is python version mismatch. What version of Python interpreter is available for the lambda layer?

> does the Lambda function need the original regorus-main files for it to work, or can I rely solely on the installed files from the Python package?

Only the python package is needed.

**Comment by anakrish** [comment] 2024-10-29 15:50
CC @Sumynwa @mfrw

**Comment by Daniel-Zafrir-1998** [comment] 2024-10-29 16:23
I really need your help i tried everything :)

**Comment by anakrish** [comment] 2024-10-29 16:30
Can you try targeting `manylinux2014_x86_64` as described here?
https://docs.aws.amazon.com/lambda/latest/dg/python-package.html

**Comment by anakrish** [comment] 2024-10-30 18:38
I'm not familiar with the details involved in creating a lambda layer.

To simplify,
> i do it in win env

Can you try it out using WSL or a Linux environment? That should eliminate any incompatibility caused by a windows environment.

Also, can you double check that the zip/wheel indeed contains a Linux shared library instead of a windows one.

**Comment by anakrish** [comment] 2024-12-09 19:02
@Daniel-Zafrir-1998 Do you have any updates on this? I'm closing this issue since there doesn't seem to be anything specific needed from Regorus at this point.

**Closed by anakrish** 2024-12-09 19:02 UTC
